server:
  port: 8080
  servlet:
    context-path: /v1.0/
  error:
    include-stacktrace: never
spring: 
  datasource:
    url: jdbc:mysql://localhost/logistica_terrestre
    username: root
    password: 3006501811Angie
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikrari:
      connection-timeout: 30000
      idle-timeout: 6000000
      max-lifetime: 1800000
      maximum-pool-size: 5
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 60000
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
jms:
  jwt:
    security:
      enabled: false
    timezone: "America/Bogota"
    issuer: ""
    token:
      auth:
        path: "/v1.0/login"
      secret: "no me conoces porque soy un secreto uwu"
      expires-in: 3600 #segundos
    excluded:
      path: "/1.0/multi"
